import { BLACK, WHITE, type Flavor } from '@protomaps/basemaps'

/**
 * Paleta extraída de los estilos por defecto de mapcn (CARTO Positron / Dark Matter),
 * adaptada al esquema Flavor de Protomaps para las teselas locales.
 *
 * @see https://basemaps.cartocdn.com/gl/positron-gl-style/style.json
 * @see https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json
 */
export const mapcnLight: Flavor = {
  ...WHITE,
  background: '#fafaf8',
  earth: '#fafaf8',
  park_a: '#eaf1e9',
  park_b: '#eaf1e9',
  wood_a: '#eaf1e9',
  wood_b: '#eaf1e9',
  scrub_a: '#eaf1e9',
  scrub_b: '#eaf1e9',
  zoo: '#eaf1e9',
  hospital: '#f0ecec',
  industrial: '#ededed',
  school: '#f2f0ea',
  pedestrian: '#f0f0ee',
  glacier: '#f5f5f5',
  sand: '#f5f2e8',
  beach: '#f5f2e8',
  aerodrome: '#f0f0ee',
  runway: '#e8e8e8',
  water: '#d4dadc',
  military: '#ededed',
  pier: '#e8e8e8',
  buildings: '#dfdfdf',

  tunnel_other_casing: '#dddddd',
  tunnel_minor_casing: '#dddddd',
  tunnel_link_casing: '#dddddd',
  tunnel_major_casing: '#dddddd',
  tunnel_highway_casing: '#dddddd',
  tunnel_other: '#eeeeee',
  tunnel_minor: '#eeeeee',
  tunnel_link: '#eeeeee',
  tunnel_major: '#eeeeee',
  tunnel_highway: '#eeeeee',

  minor_service_casing: '#dddddd',
  minor_casing: '#dddddd',
  link_casing: '#dddddd',
  major_casing_late: '#dddddd',
  highway_casing_late: '#dddddd',
  other: '#ffffff',
  minor_service: '#ffffff',
  minor_a: '#ffffff',
  minor_b: '#ffffff',
  link: '#ffffff',
  major_casing_early: '#dddddd',
  major: '#ffffff',
  highway_casing_early: '#dddddd',
  highway: '#ffffff',

  railway: '#dddddd',
  boundaries: '#c0c0c0',

  bridges_other_casing: '#dddddd',
  bridges_minor_casing: '#dddddd',
  bridges_link_casing: '#dddddd',
  bridges_major_casing: '#dddddd',
  bridges_highway_casing: '#dddddd',
  bridges_other: '#ffffff',
  bridges_minor: '#ffffff',
  bridges_link: '#ffffff',
  bridges_major: '#ffffff',
  bridges_highway: '#ffffff',

  roads_label_minor: '#999999',
  roads_label_minor_halo: '#fafaf8',
  roads_label_major: '#666666',
  roads_label_major_halo: '#fafaf8',
  ocean_label: '#7a8a90',
  subplace_label: '#8f8f8f',
  subplace_label_halo: '#fafaf8',
  city_label: '#5c5c5c',
  city_label_halo: '#fafaf8',
  state_label: '#b3b3b3',
  state_label_halo: '#fafaf8',
  country_label: '#a3a3a3',
  address_label: '#999999',
  address_label_halo: '#fafaf8',

  landcover: {
    grassland: 'rgba(234, 241, 233, 0.5)',
    barren: 'rgba(237, 237, 237, 0.25)',
    urban_area: 'rgba(237, 237, 237, 0.25)',
    farmland: 'rgba(234, 241, 233, 0.5)',
    glacier: 'rgba(245, 245, 245, 1)',
    scrub: 'rgba(234, 241, 233, 0.5)',
    forest: 'rgba(234, 241, 233, 0.5)',
  },
}

export const mapcnDark: Flavor = {
  ...BLACK,
  background: '#0e0e0e',
  earth: '#0e0e0e',
  park_a: '#0e0e0e',
  park_b: '#0e0e0e',
  wood_a: '#0e0e0e',
  wood_b: '#0e0e0e',
  scrub_a: '#0e0e0e',
  scrub_b: '#0e0e0e',
  zoo: '#0e0e0e',
  hospital: '#141414',
  industrial: '#121212',
  school: '#121212',
  pedestrian: '#121212',
  glacier: '#161616',
  sand: '#121212',
  beach: '#161616',
  aerodrome: '#121212',
  runway: '#1a1a1a',
  water: '#2c353c',
  military: '#121212',
  pier: '#1a1a1a',
  buildings: '#393939',

  tunnel_other_casing: '#0e0e0e',
  tunnel_minor_casing: '#0e0e0e',
  tunnel_link_casing: '#0e0e0e',
  tunnel_major_casing: '#0e0e0e',
  tunnel_highway_casing: '#0e0e0e',
  tunnel_other: '#1a1a1a',
  tunnel_minor: '#1a1a1a',
  tunnel_link: '#1a1a1a',
  tunnel_major: '#2a3038',
  tunnel_highway: '#2a3038',

  minor_service_casing: '#0e0e0e',
  minor_casing: '#0e0e0e',
  link_casing: '#0e0e0e',
  major_casing_late: '#0e0e0e',
  highway_casing_late: '#0e0e0e',
  other: '#161616',
  minor_service: '#0b0b0b',
  minor_a: '#1a1a1a',
  minor_b: '#1a1a1a',
  link: '#414758',
  major_casing_early: '#0e0e0e',
  major: '#414758',
  highway_casing_early: '#0e0e0e',
  highway: '#414758',

  railway: '#1a1a1a',
  boundaries: '#3d4450',

  bridges_other_casing: '#0e0e0e',
  bridges_minor_casing: '#0e0e0e',
  bridges_link_casing: '#0e0e0e',
  bridges_major_casing: '#0e0e0e',
  bridges_highway_casing: '#0e0e0e',
  bridges_other: '#1a1a1a',
  bridges_minor: '#1a1a1a',
  bridges_link: '#414758',
  bridges_major: '#414758',
  bridges_highway: '#414758',

  roads_label_minor: '#6b7280',
  roads_label_minor_halo: '#0e0e0e',
  roads_label_major: '#9ca3af',
  roads_label_major_halo: '#0e0e0e',
  ocean_label: '#6b7a82',
  subplace_label: '#6b7280',
  subplace_label_halo: '#0e0e0e',
  city_label: '#9ca3af',
  city_label_halo: '#0e0e0e',
  state_label: '#4b5563',
  state_label_halo: '#0e0e0e',
  country_label: '#6b7280',
  address_label: '#6b7280',
  address_label_halo: '#0e0e0e',

  landcover: {
    grassland: 'rgba(14, 14, 14, 1)',
    barren: 'rgba(14, 14, 14, 1)',
    urban_area: 'rgba(18, 18, 18, 1)',
    farmland: 'rgba(14, 14, 14, 1)',
    glacier: 'rgba(22, 22, 22, 1)',
    scrub: 'rgba(14, 14, 14, 1)',
    forest: 'rgba(14, 14, 14, 1)',
  },
}

export function mapcnFlavor(theme: 'light' | 'dark'): Flavor {
  return theme === 'dark' ? mapcnDark : mapcnLight
}
